- name: Install Nginx
  become: true
  ansible.builtin.apt:
    name: nginx
    state:  present

- name: Copy Nginx config file
  become: true
  copy: src=files/nginx.conf dest=/etc/nginx/sites-available/default
  notify:
    - Restart Nginx

- name: Enable Nginx config
  become: true
  file: src=/etc/nginx/sites-available/default dest=/etc/nginx/sites-enabled/default  state=link
  notify:
    - Restart Nginx

- name: Copy index.html
  become: true
  template: src=templates/index.html.j2 dest=/var/www/html/index.html mode=0644
  notify:
    - Restart Nginx

