- name: Install fava
  ansible.builtin.pip:
    name: fava
    executable: pip3

- name: Create fava service
  become: true
  copy: src=files/fava.service dest=/lib/systemd/system/fava.service

- name: Start fava service
  become: true
  service: name=fava state=started
